# Generated by Django 3.2.25 on 2024-11-30 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diffusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Diffusion_step_time', models.DateTimeField(blank=True)),
                ('Diffusion_temp', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Diffusion temp (°C) *')),
                ('Diffusion_duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='Diffusion duration (sec) *')),
                ('picture', models.FileField(blank=True, upload_to='')),
                ('content_type', models.CharField(blank=True, max_length=50)),
                ('Diffusion_notes', models.CharField(blank=True, max_length=400, null=True, verbose_name='Notes')),
            ],
        ),
        migrations.RemoveField(
            model_name='glassdeposition_p504',
            name='GlassDeposition_P504_diffusion_temp',
        ),
        migrations.RemoveField(
            model_name='glassdeposition_p504',
            name='GlassDeposition_P504_diffusion_time',
        ),
        migrations.AddField(
            model_name='chiplist',
            name='university',
            field=models.CharField(blank=True, choices=[('CMU', 'Carnegie Mellon University')], max_length=400, null=True),
        ),
        migrations.DeleteModel(
            name='GlassDeposition_700B',
        ),
        migrations.AddField(
            model_name='diffusion',
            name='chip_number',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='data_management.chiplist', verbose_name='Chip number *'),
        ),
        migrations.AddField(
            model_name='diffusion',
            name='chip_owner',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
