# Generated by Django 3.2.25 on 2024-11-25 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chiplist',
            name='starting_material',
            field=models.CharField(blank=True, default='Lightly P-doped', max_length=400, null=True),
        ),
    ]
