# Generated by Django 3.2.25 on 2024-11-25 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_management', '0002_chiplist_starting_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diffusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Diffusion_step_time', models.DateTimeField(blank=True)),
                ('Diffusion_temp', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Diffusion temp (°C) *')),
                ('Diffusion_duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='Diffusion duration (sec) *')),
                ('picture', models.FileField(blank=True, upload_to='')),
                ('content_type', models.CharField(blank=True, max_length=50)),
                ('Diffusion_notes', models.CharField(blank=True, max_length=400, null=True, verbose_name='Notes')),
                ('chip_number', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='data_management.chiplist', verbose_name='Chip number *')),
                ('chip_owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
