# Generated by Django 3.2.25 on 2024-11-30 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0002_auto_20241130_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluminumetch',
            old_name='AluminumEtch_time',
            new_name='AluminumEtch_duration',
        ),
        migrations.RenameField(
            model_name='aluminumevaporation',
            old_name='AluminumEvaporation_time',
            new_name='AluminumEvaporation_duration',
        ),
        migrations.RenameField(
            model_name='glassdeposition_p504',
            old_name='GlassDeposition_P504_bake_time',
            new_name='GlassDeposition_P504_bake_duration',
        ),
        migrations.RenameField(
            model_name='glassdeposition_p504',
            old_name='GlassDeposition_P504_prebake_time',
            new_name='GlassDeposition_P504_prebake_duration',
        ),
        migrations.RenameField(
            model_name='glassdeposition_p504',
            old_name='GlassDeposition_P504_spin_time',
            new_name='GlassDeposition_P504_spin_duration',
        ),
        migrations.RenameField(
            model_name='hfoxideetch',
            old_name='HFOxideEtch_time',
            new_name='HFOxideEtch_duration',
        ),
        migrations.RenameField(
            model_name='patterning',
            old_name='Patterning_develop_time',
            new_name='Patterning_develop_duration',
        ),
        migrations.RenameField(
            model_name='patterning',
            old_name='Patterning_exposure_time',
            new_name='Patterning_exposure_duration',
        ),
        migrations.RenameField(
            model_name='patterning',
            old_name='Patterning_hdms_bake_time',
            new_name='Patterning_hdms_bake_duration',
        ),
        migrations.RenameField(
            model_name='patterning',
            old_name='Patterning_hdms_prebake_time',
            new_name='Patterning_hdms_prebake_duration',
        ),
        migrations.RenameField(
            model_name='patterning',
            old_name='Patterning_hdms_spin_time',
            new_name='Patterning_hdms_spin_duration',
        ),
        migrations.RenameField(
            model_name='patterning',
            old_name='Patterning_photoresist_bake_time',
            new_name='Patterning_photoresist_bake_duration',
        ),
        migrations.RenameField(
            model_name='patterning',
            old_name='Patterning_photoresist_spin_time',
            new_name='Patterning_photoresist_spin_duration',
        ),
        migrations.RenameField(
            model_name='plasmaclean',
            old_name='PlasmaClean_clean_time',
            new_name='PlasmaClean_clean_duration',
        ),
        migrations.RenameField(
            model_name='plasmaetch',
            old_name='PlasmaEtch_etch_time',
            new_name='PlasmaEtch_etch_duration',
        ),
    ]
