# Generated by Django 3.2.25 on 2024-11-30 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_management', '0005_auto_20241130_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='NickelPlating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NickelPlating_step_time', models.DateTimeField(blank=True)),
                ('NickelPlating_solution', models.CharField(blank=True, choices=[('Nickelex', 'Nickelex')], max_length=400, null=True, verbose_name='Solution *')),
                ('NickelPlating_temp', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Plating temp (°C) *')),
                ('NickelPlating_duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='Plating duration (sec) *')),
                ('NickelPlating_sensitizer', models.CharField(blank=True, max_length=400, null=True, verbose_name='Sensitizer')),
                ('NickelPlating_activator', models.CharField(blank=True, max_length=400, null=True, verbose_name='Activator')),
                ('NickelPlating_surfactant', models.CharField(blank=True, max_length=400, null=True, verbose_name='Surfactant')),
                ('picture', models.FileField(blank=True, upload_to='')),
                ('content_type', models.CharField(blank=True, max_length=50)),
                ('NickelPlating_notes', models.CharField(blank=True, max_length=400, null=True, verbose_name='Notes')),
                ('chip_number', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='data_management.chiplist', verbose_name='Chip number *')),
                ('chip_owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KOHEtch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KOHEtch_step_time', models.DateTimeField(blank=True)),
                ('KOHEtch_concentration', models.PositiveIntegerField(blank=True, null=True, verbose_name='Concentration (%) *')),
                ('KOHEtch_temp', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Etch temp (°C) *')),
                ('KOHEtch_duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='Etch duration (sec) *')),
                ('KOHEtch_rpm', models.PositiveIntegerField(blank=True, null=True, verbose_name='Spin speed (rpm) *')),
                ('picture', models.FileField(blank=True, upload_to='')),
                ('content_type', models.CharField(blank=True, max_length=50)),
                ('KOHEtch_notes', models.CharField(blank=True, max_length=400, null=True, verbose_name='Notes')),
                ('chip_number', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='data_management.chiplist', verbose_name='Chip number *')),
                ('chip_owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
